name: push_checks

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install black
        run: |
          pip install --upgrade pip setuptools wheel
          pip install black
      - name: Analyze the code with black
        run: black --check .
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install -r requirements_dev.txt
          pip install -r requirements_test.txt
      - name: Run type checking
        run: pyright
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install isort
        run: |
          pip install --upgrade pip setuptools wheel
          pip install isort
      - name: Check the format of import statements
        run: isort . -c
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install ruff
        run: |
          pip install --upgrade pip setuptools wheel
          pip install ruff
      - name: Run ruff
        run: ruff check .
  test_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .
      - name: Compare outputs to expected outputs
        run: ./tests/generate.sh
  run_tests_on_generated_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
      - name: Run tests
        run: ./tests/run_tests.sh
